### ISSUE TITLE
将tailwindcss升级到3.0版本出现的class样式丢失

### ISSUE THREAD

**Issue by shqpeng** [choice-form/mono-apps#165]
top-0
   --
生成文件class为 -top-0 

inset-0
--
生成文件class为 -inset-0

inset-x-0
--
生成文件class为 -inset-x-0

>结论:tailwind2.0中文档里面当某个类加-和不加-表示的css都一致时  例如: [inset-0&-inset-0](https://www.tailwindcss.cn/docs/top-right-bottom-left)  tailwind3.0中要写为加-的类名

h5
--
之前生成文件为   

```
h5 {
  font-size: 1.25rem;
  font-size: [object Object];
}
```
之后

```
h5 {
  font-size: [object Object];
}
```
@choiceform依赖里tailwind配置:
```
    plugin(function baseAddon({ addBase, config }) {
      addBase({
        h1: { fontSize: config('theme.fontSize.5xl') },
        h2: { fontSize: config('theme.fontSize.4xl') },
        h3: { fontSize: config('theme.fontSize.3xl') },
        h4: { fontSize: config('theme.fontSize.2xl') },
        h5: { fontSize: config('theme.fontSize.xl') },
        h6: { fontSize: config('theme.fontSize.base') },
      });
    }),
```
   config('theme.fontSize.xl') 的值都是
```
[ '1.25rem', { lineHeight: '1.75rem' } ]
```
使用theme替换依赖配置可以正常显示
```    
plugin(function baseAddon({ addBase, theme }) {
      addBase({
        h1: { fontSize: theme('fontSize.5xl') },
        h2: { fontSize: theme('fontSize.4xl') },
        h3: { fontSize: theme('fontSize.3xl') },
        h4: { fontSize: theme('fontSize.2xl') },
        h5: { fontSize: theme('fontSize.1xl') },
        h6: { fontSize: theme('fontSize.base') },
      });
    }),
```

>注:将本地升级为3.0的ui-universe/core/tailwind-config  yarn link到mono-apps,还是没有效果

**Comment by nightire** [comment]
## 没有生成 .fill-current 样式

原因是我们在 @choiceform/tailwind-config 里完全重写了 `theme.color` 的定义，但是没有添加 `current: "currentColor"`。

在 Tailwind CSS 看来 `fill-current` 里的 `current` 应该代表一个颜色的定义，就如同 `transparent` 也是一种颜色的定义一样。同理还会有 `fill-black` 或者 `fill-white` 等等。而颜色的定义取决于 `theme.color` 里的内容。在默认的配置里，`current` 和 `transparent` 都是有的，如果是在其基础上扩展则不会有缺少它们之虞。但我们则是完全重写的，因此漏了 `current` 就导致了 `xxx-current` 形式的样式没有生成。

为什么在 v3 之前会生成？这个问题我也不清楚，也懒得倒回去探究了。反正要清楚 `current` 和 `transparent` 也是颜色，不能缺少它们的定义即可。

此问题已在最新发布的 `@choiceform/tailwind-config@1.0.0-rc.24` 得到修正。
