### ISSUE TITLE
di dashboard 分享出去的viewer获取dashboard资源流程

### ISSUE THREAD

**Issue by shqpeng** [choice-form/mono-apps#193]
@gongxue80 @nightire @darkbaby123 

dashboard有 `editor` 和 `viewer`两部分，本issue主要围绕的`viewer`进行流程说明，viewer 是用来浏览已发布的 dashboard 的。

#### 流程如下:

1. 用户访问viewer链接
2. 前端用链接地址中的`"token"`去获取dashboard资源(**例: https:/x/share/dashboard/DyK8tChZ中的`DyK8tChZ`)**(`统称resource_token`)
3. 接口判断当前dashboard资源`"status"`是否为`"published"`，不是则直接返回`{status: 404， code: "not_found"}`
4. 接口判断protected为`"passcode"`
    1. 为`"passode"`则去验证请求头里的`"token"`(`统称access_token`)，是否在 redis通过`"resource_token"`查询到的resource_token List中，不在则直接返回`401`
    2. 为空则直接返回相对应资源
5. 前端如果发现状态码为`401`，则提示用户，输入`"passcode"`，通过授权获取`"access_token"`
6. 接口通过`"resource_token"`校验`"passcode"` ，若密码错误则返回`{code: "public_link.invalid_passcode"，status: 422}`，code与前端约定一致即可，若正确则返回`"access_token"`,`"access_token"`可根据`"passcode"`生成,且需要将这个`"access_token"`通过`"resource_token"`作为key存入redis的list中
7.  前端获取到`"access_token"`，并把`"access_token"`存入sessionstorage，下次请求资源将`"access_token"`加到请求头里，获取资源，加载页面

因为基本是参照os-dashbaod的空间分享,所以关于接口里的一些流程不知是否完全符合

##### QUESTION:
因在editor里面访问dashboard资源的接口，都要登录系统的，所以接口需要重新开发，是开发单个接口返回所有资源，还是和目前editor获取dashbaord资源一样，多个接口去获取(因为dashboard是和轮播图一样去，点击切换，按需加载，且数据量很大,所以个人认为应该分开写)

**Comment by nightire** [comment]
> 接口判断当前dashboard资源"status"是否为"published"，不是则直接返回{status: 404， code: "not_found"}

建议这里区分两种情况，一种是 `not_found`，代表该资源不存在；另一种是 `not_published`，代表该资源存在（至少发布过一次）但目前处于未发布状态。

然后前端根据不同的 `code` 来提示用户，因为链接经常是通过 copy/paste 分享的，可以通过这个简单的区分让用户知道看不到内容到底是什么原因。（是我输错地址了，还是分享给我的人关闭了）

> 4. 接口判断protected为"passcode"

`protected` 不是 `true/false` 吗？

---

对整体流程没有异议，可以照此实施。关于最后的问题我赞同所有涉及的资源都有独立的访问接口，通过关联外键逐步获取。原因和 @shqpeng 描述的一样。

**Comment by shqpeng** [comment]
> `protected` 不是 `true/false` 吗？

写错了,确实应该是boolean
