### ISSUE TITLE
embroider 和 ember-changeset/ember-changeset-validations一起使用的bug

### ISSUE THREAD

**Issue by shqpeng** [choice-form/mono-apps#28]
### 起因
迁移过程中,发现页面不停的发送请求`/v1/teams`,
### 原因
进入页面默认会发送`/v1/teams`接口请求,如果接口发生异常就会走route/application.ts文件的error方法.
当`/v1/teams`返回401时,就会跳转到登录页**pages/login**,登录页使用了`ember-changeset`这个依赖,就会直接throw error,这个异常进入到route/application.ts文件的error方法中,又会跳转到`pages/index`,因没有token,又会跳转到登录页,如此往复
### 解决方案
更新`ember-changeset-validations`至最新版本
### 参考
https://github.com/poteto/ember-changeset/issues/527

**Comment by nightire** [comment]
@shqpeng 有对应的 PR 没？push 上来我好调试一下。

**Comment by shqpeng** [comment]
> @shqpeng 有对应的 PR 没？push 上来我好调试一下。

下午提交一版,现在登录页还点问题
